### ISSUE TITLE
Relation between System.Numerics.Vectors

### ISSUE THREAD

**Issue by SimantoR** [vimaec/Math3D#2]
I believe that this math library shouldn't reimplement the vectors, instead add to the already exisiting System.Numerics through extension methods. As System.Numerics is a part of the family of .NET Frameworks, it would be more robust and would touch a larger base of use cases.

**Comment by cdiggins** [comment]
@SimantoR  I agree, and I in fact I have done that locally. I'll push something at the end of the day.
