### ISSUE TITLE
Allow serialization

### ISSUE THREAD

**Issue by FrozenKiwi** [vimaec/Math3D#3]
To enable serialization using a Newtonsoft.Json spin-off, I have had to:

 + remove readonly from all classes
 + Add [Serializable] to all classes.

I haven't tested with the latest newtonsoft json though, and will update once done

**Comment by cdiggins** [comment]
Possibly also implement "ISerializable". For interest sake, see the Rhino API: https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_Vector3d.htm
